import type { AuditLogEntry, Badge, ClinicianCandidate, DashboardMetrics, PendingWrite, Visit } from "./types";

export const dashboardMetrics: DashboardMetrics = {
  visitsToday: 12,
  successRate: 97,
  pendingWrites: 3,
  qrAlerts: 1,
};

export const todayVisits: Visit[] = [
  {
    id: "1",
    petName: "Max Thornton",
    ownerName: "Sarah Thornton",
    species: "Dog",
    breed: "Golden Retriever",
    veterinarian: "Dr. Priya Sharma",
    reason: "Annual Wellness",
    time: "08:30 AM",
  },
  {
    id: "2",
    petName: "Luna Park",
    ownerName: "James Park",
    species: "Cat",
    breed: "Siamese",
    veterinarian: "Dr. James Okafor",
    reason: "Dental follow-up",
    time: "09:15 AM",
  },
  {
    id: "3",
    petName: "Buddy Chen",
    ownerName: "Wei Chen",
    species: "Dog",
    breed: "Labrador",
    veterinarian: "Dr. Priya Sharma",
    reason: "Vaccination",
    time: "10:00 AM",
  },
  {
    id: "4",
    petName: "Mochi Lee",
    ownerName: "Amy Lee",
    species: "Cat",
    breed: "Persian",
    veterinarian: "Dr. Alex Miller",
    reason: "Skin irritation",
    time: "11:30 AM",
  },
  {
    id: "5",
    petName: "Bella",
    ownerName: "Tom Rivera",
    species: "Dog",
    breed: "Beagle",
    veterinarian: "Dr. Jane Doe",
    reason: "Post-surgery check",
    time: "01:00 PM",
  },
  {
    id: "6",
    petName: "Charlie",
    ownerName: "Nina Patel",
    species: "Dog",
    breed: "Poodle",
    veterinarian: "Dr. James Okafor",
    reason: "Ear infection",
    time: "02:00 PM",
  },
  {
    id: "7",
    petName: "Whiskers",
    ownerName: "Emma Wilson",
    species: "Cat",
    breed: "Maine Coon",
    veterinarian: "Dr. Alex Miller",
    reason: "Weight check",
    time: "02:45 PM",
  },
  {
    id: "8",
    petName: "Rocky",
    ownerName: "Mike Johnson",
    species: "Dog",
    breed: "Bulldog",
    veterinarian: "Dr. Priya Sharma",
    reason: "Allergy follow-up",
    time: "03:30 PM",
  },
  {
    id: "9",
    petName: "Coco",
    ownerName: "Lisa Brown",
    species: "Dog",
    breed: "Shih Tzu",
    veterinarian: "Dr. Jane Doe",
    reason: "Grooming consult",
    time: "04:00 PM",
  },
  {
    id: "10",
    petName: "Simba",
    ownerName: "David Kim",
    species: "Cat",
    breed: "Bengal",
    veterinarian: "Dr. James Okafor",
    reason: "Behavior consult",
    time: "04:30 PM",
  },
  {
    id: "11",
    petName: "Daisy",
    ownerName: "Rachel Green",
    species: "Dog",
    breed: "Cocker Spaniel",
    veterinarian: "Dr. Alex Miller",
    reason: "Medication refill",
    time: "05:00 PM",
  },
  {
    id: "12",
    petName: "Oliver",
    ownerName: "Chris Evans",
    species: "Dog",
    breed: "Dachshund",
    veterinarian: "Dr. Priya Sharma",
    reason: "Routine checkup",
    time: "05:30 PM",
  },
];

export const pendingWrites: PendingWrite[] = [
  { id: "1", petName: "Max Thornton", phms: "CORNERSTONE", status: "pending" },
  { id: "2", petName: "Oliver Kim", phms: "NEO", status: "pending" },
  { id: "3", petName: "Bella Cruz", phms: "CORNERSTONE", status: "pending" },
];

export const badgeRegistry: Badge[] = [
  {
    id: "badge-1",
    clinicianName: "Dr. Jane Doe",
    email: "jane.doe@clinic.com",
    role: "Senior Veterinarian",
    status: "ACTIVE",
    lastIssued: "Oct 12, 2023",
  },
  {
    id: "badge-2",
    clinicianName: "Marcus Bennett",
    email: "m.bennett@clinic.com",
    role: "Veterinarian",
    status: "DEACTIVATED",
    lastIssued: "Sep 05, 2023",
  },
  {
    id: "badge-3",
    clinicianName: "Sarah Lopez",
    email: "s.lopez@clinic.com",
    role: "Veterinary Surgeon",
    status: "LOST",
    lastIssued: "Jan 18, 2024",
  },
  {
    id: "badge-4",
    clinicianName: "Dr. Alex Miller",
    email: "a.miller@clinic.com",
    role: "Veterinary Surgeon",
    status: "NO_BADGE",
    lastIssued: null,
  },
];

export const clinicianCandidates: ClinicianCandidate[] = [
  {
    id: "cand-1",
    name: "Dr. Alex Rivera",
    role: "Senior Veterinarian",
    email: "alex.rivera@clinic.com",
  },
  {
    id: "cand-2",
    name: "Dr. Sarah Chen",
    role: "Veterinary Surgeon",
    email: "sarah.chen@clinic.com",
  },
  {
    id: "cand-3",
    name: "Jamie Lance",
    role: "Veterinarian",
    email: "jamie.lance@clinic.com",
  },
  {
    id: "badge-4",
    name: "Dr. Alex Miller",
    role: "Veterinary Surgeon",
    email: "a.miller@clinic.com",
  },
];

export const wakePhraseExamples = [
  "Hey CarePilot, start visit for Max Thornton",
  "Hey CarePilot, add vaccination note",
  "Hey CarePilot, schedule follow-up in two weeks",
  "Hey CarePilot, send summary to Cornerstone",
];

export const auditLogEntries: AuditLogEntry[] = [
  {
    id: "1",
    timestamp: "Jun 16, 2026 09:12 AM",
    user: "Siri Reddy",
    action: "Badge issued",
    details: "Issued badge for Dr. Jane Doe",
  },
  {
    id: "2",
    timestamp: "Jun 16, 2026 08:45 AM",
    user: "Siri Reddy",
    action: "PHMS write retry",
    details: "Retried write-back for Max Thornton (Cornerstone)",
  },
  {
    id: "3",
    timestamp: "Jun 15, 2026 04:30 PM",
    user: "Siri Reddy",
    action: "Wake phrase updated",
    details: "Changed wake phrase to 'Hey CarePilot'",
  },
  {
    id: "4",
    timestamp: "Jun 15, 2026 02:15 PM",
    user: "Siri Reddy",
    action: "PIN regenerated",
    details: "Regenerated PIN for Marcus Bennett badge",
  },
];
